name: CI Pipeline

on:
  pull_request:
    branches:
      - main # Or specify the branch you want to target

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine

    steps:
      # Checkout the code from the pull request
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Rust environment (using Alpine image, so need to install some dependencies)
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: "stable"

      # Install dependencies for both Rust and Node.js
      - name: Install Rust dependencies
        run: |
          cd apps/backend
          cargo install --locked

      - name: Install Node.js dependencies from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: apps/frontend/.nvmrc # Automatically detects Node.js version from .nvmrc

      - name: Install Node.js packages
        run: |
          cd apps/frontend
          bun install  # Using Bun to install Node.js dependencies

      # Run Rust tests, check and build for my sanity.
      - name: Run Cargo Check
        run: |
          cd apps/backend
          cargo check

      - name: Run Cargo Tests
        run: |
          cd apps/backend
          cargo test

      - name: Run Cargo Tests
        run: |
          cd apps/backend
          cargo build --release

      # Run Bun lint
      - name: Run Bun Lint
        run: |
          cd apps/frontend
          bun run lint

      # Run Bun build
      - name: Run Bun Build
        run: |
          cd apps/frontend
          bun run build
